
services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: oral_app_api_gateway
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client-app
      - user-service
      - comms-service
      - ai-omni-service
      - conversation-service
    networks:
      - oral_app_net

  client-app:
    build: ./client
    container_name: oral_app_client_app
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - oral_app_net

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./services/user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oral_app_net

  mongo:
    image: mongo:6.0
    container_name: oral_app_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - oral_app_net

  redis:
    image: redis:7-alpine
    container_name: oral_app_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - oral_app_net

  user-service:
    build: ./services/user-service
    container_name: oral_app_user_service
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./services/user-service/src:/usr/src/app/src
      - ./services/user-service/node_modules:/usr/src/app/node_modules
    env_file:
      - ./.env
      - ./services/user-service/.env
    depends_on:
      - postgres
    networks:
      - oral_app_net

  comms-service:
    build: ./services/comms-service
    container_name: oral_app_comms_service
    restart: always
    env_file:
      - ./services/comms-service/.env
    depends_on:
      - redis
    networks:
      - oral_app_net

  ai-omni-service:
    build: ./services/ai-omni-service
    container_name: oral_app_ai_omni_service
    restart: always
    ports:
      - "8082:8082"
      - "8081:8081"
    volumes:
      - ./services/ai-omni-service/models:/usr/src/app/models
      - ./services/ai-omni-service/.env:/usr/src/app/.env
    networks:
      - oral_app_net

  conversation-service:
    build: ./services/conversation-service
    container_name: oral_app_conversation_service
    restart: always
    networks:
      - oral_app_net

volumes:
  postgres_data:
  mongo_data:

networks:
  oral_app_net:
    driver: bridge