
services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: oral_app_api_gateway
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - oral_app_net

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: oral_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - oral_app_net

  mongo:
    image: mongo:6.0
    container_name: oral_app_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - oral_app_net

  redis:
    image: redis:7-alpine
    container_name: oral_app_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - oral_app_net

  user-service:
    build: ./services/user-service
    container_name: oral_app_user_service
    restart: always
    volumes:
      - ./services/user-service/src:/usr/src/app/src
      - ./services/user-service/node_modules:/usr/src/app/node_modules
    env_file:
      - ./services/user-service/.env
    depends_on:
      - postgres
    networks:
      - oral_app_net

  comms-service:
    build: ./services/comms-service
    container_name: oral_app_comms_service
    restart: always
    env_file:
      - ./services/comms-service/.env
    networks:
      - oral_app_net

  ai-omni-service:
    build: ./services/ai-omni-service
    container_name: oral_app_ai_omni_service
    restart: always
    ports:
      - "8082:8082"
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    networks:
      - oral_app_net

  conversation-service:
    build: ./services/conversation-service
    container_name: oral_app_conversation_service
    restart: always
    networks:
      - oral_app_net

volumes:
  postgres_data:
  mongo_data:

networks:
  oral_app_net:
    driver: bridge